sales_testing_dbt:
  outputs:
    dev:
      dataset: warehouse_sales
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/plugins/key_file.json
      location: asia-southeast1
      method: service-account
      priority: interactive
      project: project-azhar-385817
      threads: 1
      type: bigquery
  target: dev